### ISSUE TITLE
Grammar in app.py

### ISSUE THREAD

**Issue by darkmjblink** [r-dataisbeautiful/dataisbeautiful-bot#2]
https://github.com/r-dataisbeautiful/dataisbeautiful-bot/blob/73e254d3f56acec45804974fd85ece88da4645c2/app.py#L23

I don't know how to properly edit this and wouldn't want to break something. Just noticed some errors in the grammar probably due to the sentences being reworded at some point. 

"Post approval does not signify **this the** visualization has been verified or its sources checked." should be "Post approval does not signify **that the** visualization has been verified or its sources checked."

Also, the last line about remixing ends with "with the data **in the in the** author\'s citation." which should just be "with the data **in the** author\'s citation."

Thanks

**Comment by atbuy** [comment]
I made a PR for the formatting, because the reply was a really long one-line string so I changed it to be more readable, but I didn't notice the grammar. Make a PR if you think it should be corrected.

**Comment by gm3197** [comment]
Thanks for pointing this out. This has been resolved.
